=== JAVIALV22/sonora-web-semantica/canciones.dtd
<!ELEMENT cancionero (cancion+)>
<!ELEMENT cancion (titulo, artista, album, duracion, anio, audio)>
<!ATTLIST cancion
  id ID #REQUIRED
  genero (pop|rock|latino|balada|reggaeton|salsa|regional) #REQUIRED
>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT audio (#PCDATA)>

=== JAVIALV22/sonora-web-semantica/canciones.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="canciones.xsl?v=4"?>
<!DOCTYPE cancionero SYSTEM "canciones.dtd">
<cancionero>
  <cancion id="c1" genero="pop">
    <titulo>Billie Jean</titulo>
    <artista>Michael Jackson</artista>
    <album>Thriller</album>
    <duracion>4:54</duracion>
    <anio>1982</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3</audio>
  </cancion>
  <cancion id="c2" genero="rock">
    <titulo>Bohemian Rhapsody</titulo>
    <artista>Queen</artista>
    <album>A Night at the Opera</album>
    <duracion>5:55</duracion>
    <anio>1975</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3</audio>
  </cancion>
  <cancion id="c3" genero="pop">
    <titulo>Shape of You</titulo>
    <artista>Ed Sheeran</artista>
    <album>Divide</album>
    <duracion>3:53</duracion>
    <anio>2017</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3</audio>
  </cancion>
  <cancion id="c4" genero="latino">
    <titulo>Vivir Mi Vida</titulo>
    <artista>Marc Anthony</artista>
    <album>3.0</album>
    <duracion>4:12</duracion>
    <anio>2013</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3</audio>
  </cancion>
  <cancion id="c5" genero="balada">
    <titulo>Someone Like You</titulo>
    <artista>Adele</artista>
    <album>21</album>
    <duracion>4:45</duracion>
    <anio>2011</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3</audio>
  </cancion>
  <cancion id="c6" genero="reggaeton">
    <titulo>Ojitos Lindos</titulo>
    <artista>Bad Bunny</artista>
    <album>Un Verano Sin Ti</album>
    <duracion>4:18</duracion>
    <anio>2022</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3</audio>
  </cancion>
  <cancion id="c7" genero="rock">
    <titulo>Smells Like Teen Spirit</titulo>
    <artista>Nirvana</artista>
    <album>Nevermind</album>
    <duracion>5:01</duracion>
    <anio>1991</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3</audio>
  </cancion>
  <cancion id="c8" genero="salsa">
    <titulo>La Rebelion</titulo>
    <artista>Joe Arroyo</artista>
    <album>Fuego en Mi Mente</album>
    <duracion>4:50</duracion>
    <anio>1986</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3</audio>
  </cancion>
  <cancion id="c9" genero="pop">
    <titulo>Blinding Lights</titulo>
    <artista>The Weeknd</artista>
    <album>After Hours</album>
    <duracion>3:20</duracion>
    <anio>2019</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3</audio>
  </cancion>
  <cancion id="c10" genero="regional">
    <titulo>Ella Baila Sola</titulo>
    <artista>Eslabon Armado y Peso Pluma</artista>
    <album>Desvelado</album>
    <duracion>2:45</duracion>
    <anio>2023</anio>
    <audio>https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3</audio>
  </cancion>
</cancionero>
